### ISSUE TITLE
From SAP HANA to BigQuery

### ISSUE THREAD

**Issue by wruter** [SAP/datahub-integration-examples#3]
Hello team,
I know it not a so-called issue, but i can't find any place where to ask you a question. I look at the example of how to expose Hana data via OpenAPI, which is good, but i'm wondering if there a way to create a specific connector or way to export data out of Hana to BigQuery on straight to GCS ?
Thanks for your answer and sorry for using this to open a message.
Williams

**Comment by flegler** [comment]
I think you should be able to work with the default connectors. E.g. in Data Hub 2.4 we have:
 - a HANAClient operator to connect to HANA (read and write)
 - 2 Google BigQuery operators to consume BigQuery
 - ReadFile, WriteFile operators to read/write from GCS

You could ask such questions on https://answers.sap.com/index.html and tag them with 'SAP Data Hub'
